
let EYBenchmarks = [{id:'1', bc:'Procure to Pay',pl1:'Procurement',bm:'Total cost of the process "develop sourcing strategies" per 1,000 revenue',bp:'2.80',md:'0.65',tp:'0.18'},
{id:'2', bc:'Procure to Pay',pl1:'Procurement',bm:'Total cost of the process "develop sourcing strategies" per 1,000 purchases',bp:'6.03',md:'1.76',tp:'0.61'},
{id:'3', bc:'Procure to Pay',pl1:'Procurement',bm:'Personnel cost of the process "develop sourcing strategies" per 1,000  revenue',bp:'1.49',md:'0.34',tp:'0.11'},
{id:'4', bc:'Procure to Pay',pl1:'Procurement',bm:'Personnel cost of the process "develop sourcing strategies" per 1,000 purchases',bp:'3.43',md:'1.15',tp:'0.37'},
{id:'5', bc:'Procure to Pay',pl1:'Procurement',bm:'Systems cost of the process "develop sourcing strategies" per 100,000  revenue',bp:'19.25',md:'2.68',tp:'0.50'},
{id:'6', bc:'Procure to Pay',pl1:'Procurement',bm:'Systems cost of the process "develop sourcing strategies" per 100,000 purchases',bp:'46.37',md:'7.70',tp:'1.17'},
{id:'7', bc:'Procure to Pay',pl1:'Procurement',bm:'Number of FTEs for the process "develop sourcing strategies" per 1 billion revenue',bp:'21.35',md:'4.48',tp:'1.37'},
{id:'8', bc:'Procure to Pay',pl1:'Procurement',bm:'Number of FTEs for the process "develop sourcing strategies" per 1 billion purchases ',bp:'46.33',md:'14.35',tp:'4'},
{id:'9', bc:'Procure to Pay',pl1:'Procurement',bm:'Total cost of the process "select suppliers & develop & maintain contracts" per 1,000 revenue',bp:'2.41',md:'0.81',tp:'0.27'},
{id:'10', bc:'Procure to Pay',pl1:'Procurement',bm:'Total cost of the process "select suppliers & develop/maintain contracts" per 1,000 purchases',bp:'6.35',md:'2.57',tp:'0.83'},
{id:'11', bc:'Procure to Pay',pl1:'Procurement',bm:'Personnel cost of the process "select suppliers & develop/maintain contracts" per 1,000 revenue',bp:'1.35',md:'0.41',tp:'0.17'},
{id:'12', bc:'Procure to Pay',pl1:'Procurement',bm:'Personnel cost of the process "select suppliers & develop/maintain contracts" per 1,000 purchases',bp:'4.52',md:'1.56',tp:'0.51'},
{id:'13', bc:'Procure to Pay',pl1:'Procurement',bm:'Systems cost of the process "select suppliers & develop & maintain contracts" per 100,000 revenue ',bp:'20.10',md:'3.63',tp:'0.73'},
{id:'14', bc:'Procure to Pay',pl1:'Procurement',bm:'Systems cost of the process "select suppliers & develop & maintain contracts" per 100,000 purchases',bp:'70.97',md:'12.10',tp:'2.39'},
{id:'15', bc:'Procure to Pay',pl1:'Procurement',bm:'Number of FTEs for the process "select suppliers and develop & maintain contracts" per 1 billion revenue',bp:'21.15',md:'6.03',tp:'2.08'},
{id:'16', bc:'Procure to Pay',pl1:'Procurement',bm:'Number of FTEs for the process "select suppliers and develop/maintain contracts" per 1 billion purchases',bp:'58.76',md:'24.69',tp:'7.76'},
{id:'17', bc:'Procure to Pay',pl1:'Procurement',bm:'Percentage of annual purchases value from certified vendors',bp:'0.25',md:'0.75',tp:'0.95'},
{id:'18', bc:'Procure to Pay',pl1:'Procurement',bm:'Total cost of the process "order materials/services" per 1,000 revenue',bp:'4.51',md:'1.53',tp:'0.42'},
{id:'19', bc:'Procure to Pay',pl1:'Procurement',bm:'Total cost of the process "order materials/services" per 1,000 purchases',bp:'12.74',md:'4.14',tp:'1.46'},
{id:'20', bc:'Procure to Pay',pl1:'Procurement',bm:'Total cost of the process "order materials/services" per purchase order line item',bp:'55.07',md:'17.35',tp:'3.32'},
{id:'21', bc:'Procure to Pay',pl1:'Procurement',bm:'Personnel cost of the process "order materials/services" per 1,000 revenue',bp:'3.05',md:'0.94',tp:'0.24'},
{id:'22', bc:'Procure to Pay',pl1:'Procurement',bm:'Personnel cost of the process "order materials/services" per 1,000 purchases',bp:'7.54',md:'2.60',tp:'1.05'},
{id:'23', bc:'Procure to Pay',pl1:'Procurement',bm:'Systems cost of the process "order materials/services" per 100,000  revenue',bp:'23.90',md:'6.43',tp:'1.36'},
{id:'24', bc:'Procure to Pay',pl1:'Procurement',bm:'Systems cost of the process "order materials/services" per 100,000 purchases',bp:'83.22',md:'21.28',tp:'3.71'},
{id:'25', bc:'Procure to Pay',pl1:'Procurement',bm:'Number of purchase orders processed per "order materials/services" FTE',bp:'655.2',md:'1700',tp:'4810.22'},
{id:'26', bc:'Procure to Pay',pl1:'Procurement',bm:'Number of purchase order line items processed per "order materials/services" FTE',bp:'2059.53',md:'4690.48',tp:'19124.69'},
{id:'27', bc:'Procure to Pay',pl1:'Procurement',bm:'Percentage of purchase orders approved electronically',bp:'0',md:'0.9',tp:'1'},
{id:'28', bc:'Procure to Pay',pl1:'Procurement',bm:'Number of FTEs for the process "order materials/services" per 1 billion revenue',bp:'57.43',md:'17.1',tp:'3.93'},
{id:'29', bc:'Procure to Pay',pl1:'Procurement',bm:'Number of FTEs for the process "order materials/services" per 1 billion purchases',bp:'138.06',md:'44.5',tp:'17.33'},
{id:'30', bc:'Procure to Pay',pl1:'Procurement',bm:'Cycle time in hours to place purchase order',bp:'48',md:'24',tp:'3'},
{id:'31', bc:'Procure to Pay',pl1:'Procurement',bm:'Total cost of the process "appraise and develop suppliers" per 1,000 revenue',bp:'1.52',md:'0.45',tp:'0.16'},
{id:'32', bc:'Procure to Pay',pl1:'Procurement',bm:'Total cost of the process "appraise and develop suppliers" per 1,000 purchases',bp:'3.39',md:'1.20',tp:'0.43'},
{id:'33', bc:'Procure to Pay',pl1:'Procurement',bm:'Personnel cost of the process "appraise and develop suppliers" per 1,000 revenue',bp:'1.01',md:'0.25',tp:'0.07'},
{id:'34', bc:'Procure to Pay',pl1:'Procurement',bm:'Personnel cost of the process "appraise and develop suppliers" per 1,000 purchases',bp:'2.45',md:'0.69',tp:'0.22'},
{id:'35', bc:'Procure to Pay',pl1:'Procurement',bm:'Systems cost of the process "appraise and develop suppliers" per 100,000 revenue',bp:'9.06',md:'1.54',tp:'0.42'},
{id:'36', bc:'Procure to Pay',pl1:'Procurement',bm:'Systems cost of the process "appraise and develop suppliers" per 100,000 purchases',bp:'21.42',md:'5.30',tp:'1.25'},
{id:'37', bc:'Procure to Pay',pl1:'Procurement',bm:'Total number of active vendors in the master file per 1 million purchases',bp:'19.61',md:'5.55',tp:'1.21'},
{id:'38', bc:'Procure to Pay',pl1:'Procurement',bm:'Number of FTEs for the process "appraise and develop suppliers" per 1 billion revenue',bp:'16.04',md:'4.07',tp:'1'},
{id:'39', bc:'Procure to Pay',pl1:'Procurement',bm:'Number of FTEs for the process "appraise and develop suppliers" per 1 billion purchases',bp:'36.74',md:'10.89',tp:'2.86'},
{id:'40', bc:'Procure to Pay',pl1:'Procurement',bm:'Total cost of the procurement cycle per purchase order',bp:'503.58',md:'156.25',tp:'53.82'},
{id:'41', bc:'Procure to Pay',pl1:'Procurement',bm:'Total cost of the procurement cycle per procurement cycle FTE',bp:'167,823.02',md:'111,900.20',tp:'72,897.72'},
{id:'42', bc:'Procure to Pay',pl1:'Procurement',bm:'Systems cost of the procurement cycle as a percentage of total cost of the procurement cycle',bp:'0.1053',md:'0.0495',tp:'0.0168'},
{id:'43', bc:'Procure to Pay',pl1:'Procurement',bm:'Total cost of the procurement cycle per 1,000 revenue',bp:'12.08',md:'4.97',tp:'1.40'},
{id:'44', bc:'Procure to Pay',pl1:'Procurement',bm:'Total cost of the procurement cycle per 1,000 purchases',bp:'26.91',md:'13.37',tp:'5.38'},
{id:'45', bc:'Procure to Pay',pl1:'Procurement',bm:'Total number of purchase orders processed per procurement FTE',bp:'270.33',md:'723.24',tp:'2067.55'},
{id:'46', bc:'Procure to Pay',pl1:'Procurement',bm:'Total number of active suppliers in vendor masterfile per procurement FTE',bp:'156.09',md:'37.39',tp:'8.09'},
{id:'47', bc:'Procure to Pay',pl1:'Procurement',bm:'Number of FTEs for the procurement cycle per 1 billion revenue',bp:'109.07',md:'41.42',tp:'12.2'},
{id:'48', bc:'Procure to Pay',pl1:'Procurement',bm:'Number of FTEs for the procurement cycle per 1 billion purchases',bp:'273.98',md:'100.31',tp:'47.39'},
{id:'49', bc:'Procure to Pay',pl1:'Procurement',bm:'Direct materials and services value as a percentage of total annual value of purchases',bp:'0.2697',md:'0.7092',tp:'0.9313'},
{id:'50', bc:'Procure to Pay',pl1:'Procurement',bm:'Percentage of total value of direct materials and services purchased outside of country*',bp:'0',md:'0.12',tp:'0.45'},
{id:'51', bc:'Procure to Pay',pl1:'Procurement',bm:'Percentage of your sites total annual purchases procured via maverick buying',bp:'0.2',md:'0.05',tp:'0'},
{id:'52', bc:'Procure to Pay',pl1:'Procurement',bm:'Percentage of total annual value of materials and services purchases included in Total Cost of Ownership mode',bp:'0',md:'0.1',tp:'0.8'},
{id:'53', bc:'Procure to Pay',pl1:'Procurement',bm:'Average transaction amount per purchase order',bp:'2,081.60',md:'8,931.00',tp:'25,000.00'},
{id:'54', bc:'Procure to Pay',pl1:'Procurement',bm:'Value of materials and service per 1,000 revenue',bp:'632.81',md:'407.55',tp:'159.91'},
{id:'55', bc:'Procure to Pay',pl1:'Procurement',bm:'Percentage of purchase order line items transacted using e-procurement enabled catalogue suppliers',bp:'0',md:'0.0025',tp:'0.25'},
{id:'56', bc:'Procure to Pay',pl1:'Procurement',bm:'Strategic suppliers as a percentage of all active suppliers',bp:'0.0106',md:'0.041',tp:'0.1709'},
{id:'57', bc:'Procure to Pay',pl1:'Procurement',bm:'Indirect materials and services value as a percentage of total annual value of purchases',bp:'0.7304',md:'0.2941',tp:'0.071'},
{id:'58', bc:'Procure to Pay',pl1:'Procurement',bm:'Percentage of the total value of annual purchases allocated among the following purchase arrangement type: individual purchase orders*',bp:'0.2',md:'0.6113',tp:'0.9211'},
{id:'59', bc:'Procure to Pay',pl1:'Procurement',bm:'Percentage of the total value of annual purchases allocated among the following purchase type: blanket/contract orders*',bp:'0.0146',md:'0.1943',tp:'0.5882'},
{id:'60', bc:'Procure to Pay',pl1:'Procurement',bm:'Percentage of the total value of annual purchases allocated among the following arrangement type: procurement cards *',bp:'0',md:'0.0039',tp:'0.0444'},
{id:'61', bc:'Procure to Pay',pl1:'Procurement',bm:'Percentage of total value of annual purchases allocated among the following purchase arrangement type: replenishment/vendor management inventor *',bp:'0',md:'0.0039',tp:'0.108'},
{id:'62', bc:'Procure to Pay',pl1:'Procurement',bm:'Percentage of total value of annual purchases allocated among the following arrangement type: other *',bp:'0',md:'0',tp:'0.1807'},
{id:'63', bc:'Procure to Pay',pl1:'Procurement',bm:'Percentage of total value of annual purchases allocated among the following submission method: internet *',bp:'0',md:'0.0109',tp:'0.577'},
{id:'64', bc:'Procure to Pay',pl1:'Procurement',bm:'Percentage of total value of annual purchases allocated among the following submission method: wireless application protocol*',bp:'0',md:'0',tp:'0'},
{id:'65', bc:'Procure to Pay',pl1:'Procurement',bm:'Percentage of total value of annual purchases allocated among the following submission method: electronic data exchange*',bp:'0',md:'0.0057',tp:'0.4426'},
{id:'66', bc:'Procure to Pay',pl1:'Procurement',bm:'Percentage of total value of annual purchases allocated among the following submission method: fax*',bp:'0.0164',md:'0.1852',tp:'0.6199'},
{id:'67', bc:'Procure to Pay',pl1:'Procurement',bm:'Percentage of total value of annual purchases allocated among the following submission method: mail *',bp:'0',md:'0.01',tp:'0.4154'},
{id:'68', bc:'Procure to Pay',pl1:'Procurement',bm:'Percentage of total value of annual purchases allocated among the following submission method: telephone*',bp:'0',md:'0',tp:'0.1201'},
{id:'69', bc:'Procure to Pay',pl1:'Procurement',bm:'Percentage of the total value of annual purchases allocated among the following submission method: other*',bp:'0',md:'0',tp:'0.2764'},
{id:'70', bc:'Procure to Pay',pl1:'Procurement',bm:'Average supplier lead time on purchased materials',bp:'45',md:'18',tp:'6'},
{id:'71', bc:'Procure to Pay',pl1:'Procurement',bm:'Annual raw material inventory turn rate',bp:'3',md:'6',tp:'12.55'},
{id:'72', bc:'Procure to Pay',pl1:'Procurement',bm:'Total cost of the process "order materials/services" per purchase order',bp:'156.35',md:'45.83',tp:'14.48'},
{id:'73', bc:'Procure to Pay',pl1:'Procurement',bm:'Total cost of the procurement cycle per purchase order line item',bp:'137.08',md:'47.29',tp:'11.61'},
{id:'74', bc:'Procure to Pay',pl1:'Procurement',bm:'Total cost of the procurement cycle as a percentage of Cost of Goods Sold (COGS)',bp:'0.0224',md:'0.0084',tp:'0.0033'},
{id:'75', bc:'Procure to Pay',pl1:'Procurement',bm:'Total purchase value (spend, in thousands of dollars) per procurement FTE',bp:'3,650.30',md:'9,968.90',tp:'21,100.17'},
{id:'76', bc:'Procure to Pay',pl1:'Procurement',bm:'Days payable',bp:'54.24',md:'36.25',tp:'25.03'},
{id:'77', bc:'Procure to Pay',pl1:'Procurement',bm:'Procure to Pay',bp:'79.6',md:'53.45',tp:'30'},
{id:'78', bc:'Procure to Pay',pl1:'Procurement',bm:'Percentage of supplier orders received by original request date (on time)',bp:'0.7',md:'0.85',tp:'0.95'},
{id:'79', bc:'Procure to Pay',pl1:'Procurement',bm:'Percentage of purchase orders received complete',bp:'0.8',md:'0.9',tp:'0.98'},
{id:'80', bc:'Procure to Pay',pl1:'Procurement',bm:'Percentage of purchase order line items received complete',bp:'0.816',md:'0.93',tp:'0.98'},
{id:'81', bc:'Procure to Pay',pl1:'Procurement',bm:'Percentage of total annual number of goods receipts received without item and quantity verification',bp:'0',md:'0',tp:'0.0507'},
{id:'82', bc:'Procure to Pay',pl1:'Procurement',bm:'Percentage of purchase orders received damage free',bp:'0.9454',md:'0.9801',tp:'0.9949'},
{id:'83', bc:'Procure to Pay',pl1:'Procurement',bm:'Percentage of purchase order line items received damage free',bp:'0.95',md:'0.99',tp:'0.9976'},
{id:'84', bc:'Procure to Pay',pl1:'Procurement',bm:'Percentage of total annual number of items purchased received fail inspection (incoming material quality)',bp:'0.0312',md:'0.0082',tp:'0.0009'},
{id:'85', bc:'Procure to Pay',pl1:'Procurement',bm:'Percentage of annual value of purchased material that is received from vendors that participate in vendor-managed inventory programs',bp:'0',md:'0.05',tp:'0.3'},
{id:'86', bc:'Procure to Pay',pl1:'Procurement',bm:'Percentage of the total value of annual purchases placed by non-traditional submission methods (without a buyer or purchasing agent being involved to process the transaction)',bp:'0.0005',md:'0.4516',tp:'0.8863'},
{id:'87', bc:'Procure to Pay',pl1:'Procurement',bm:'Cost of goods sold as a percentage of revenue',bp:'0.8304',md:'0.6492',tp:'0.3656'},
{id:'88', bc:'Procure to Pay',pl1:'Accounts Payable',bm:'Total cost of the process "process accounts payable1” per invoice processed',bp:'2.86',md:'7.49',tp:'2.86'},
{id:'89', bc:'Procure to Pay',pl1:'Accounts Payable',bm:'Total cost for the process to perform accounts payable1 per 1,000 of revenue',bp:'0.37',md:'0.84',tp:'0.37'},
{id:'90', bc:'Procure to Pay',pl1:'Accounts Payable',bm:'Personnel cost of the process to perform accounts payable1 per 1,000 revenue',bp:'0.22',md:'0.59',tp:'0.22'},
{id:'91', bc:'Procure to Pay',pl1:'Accounts Payable',bm:'Systems cost of the process to perform accounts payable1 per 100K of revenue',bp:'2.41',md:'6.67',tp:'2.41'},
{id:'92', bc:'Procure to Pay',pl1:'Accounts Payable',bm:'Number of invoices processed per "process accounts payable" FTE',bp:'18921.3',md:'9000',tp:'18921.3'},
{id:'93', bc:'Procure to Pay',pl1:'Accounts Payable',bm:'Percentage of invoice line items that are matched the first time',bp:'0.939',md:'0.615',tp:'0.939'},
{id:'94', bc:'Procure to Pay',pl1:'Accounts Payable',bm:'Percentage use of EDI for receiving invoices and for entering them onto the system',bp:'0.417',md:'0',tp:'0.417'},
{id:'95', bc:'Procure to Pay',pl1:'Accounts Payable',bm:'Number of FTEs performing the accounts payable process1 per 1 billion revenue',bp:'5',md:'13',tp:'5'},
{id:'96', bc:'Procure to Pay',pl1:'Accounts Payable',bm:'Percentage of invoice line items matched with a purchase order',bp:'0.9',md:'0.676',tp:'0.9'},
{id:'97', bc:'Procure to Pay',pl1:'Accounts Payable',bm:'Cycle time in hours to enter invoice data onto the system',bp:'12.3',md:'40',tp:'12.3'},
{id:'98', bc:'Procure to Pay',pl1:'Accounts Payable',bm:'Cycle time in days from receipt of invoice until approved and scheduled for payment',bp:'4',md:'7',tp:'4'},
{id:'99', bc:'Procure to Pay',pl1:'Accounts Payable',bm:'Cycle time in days to resolve an invoice error',bp:'3',md:'6.9',tp:'3'},
{id:'100', bc:'Procure to Pay',pl1:'Accounts Payable',bm:'Cycle time in days from receipt of invoice until payment is transmitted',bp:'12',md:'30',tp:'12'},
{id:'101', bc:'Procure to Pay',pl1:'Accounts Payable',bm:'Total cost of the process "process accounts payable1” per invoice processed',bp:'20.25',md:'7.49',tp:'2.86'},
{id:'102', bc:'Procure to Pay',pl1:'Accounts Payable',bm:'Total cost for the process to perform accounts payable1 per 1,000 of revenue',bp:'1.90',md:'0.84',tp:'0.37'},
{id:'103', bc:'Procure to Pay',pl1:'Accounts Payable',bm:'Personnel cost of the process to perform accounts payable1 per 1,000 revenue',bp:'1.12',md:'0.59',tp:'0.22'},
{id:'104', bc:'Procure to Pay',pl1:'Accounts Payable',bm:'Systems cost of the process to perform accounts payable1 per 100K of revenue',bp:'23.17',md:'6.67',tp:'2.41'},
{id:'105', bc:'Procure to Pay',pl1:'Accounts Payable',bm:'Number of invoices processed per "process accounts payable" FTE',bp:'4234.4',md:'9000',tp:'18921.3'},
{id:'106', bc:'Procure to Pay',pl1:'Accounts Payable',bm:'Percentage of invoice line items that are matched the first time',bp:'0.25',md:'0.615',tp:'0.939'},
{id:'107', bc:'Procure to Pay',pl1:'Accounts Payable',bm:'Percentage use of EDI for receiving invoices and for entering them onto the system',bp:'0',md:'0',tp:'0.417'},
{id:'108', bc:'Procure to Pay',pl1:'Accounts Payable',bm:'Number of FTEs performing the accounts payable process1 per 1 billion revenue',bp:'31',md:'13',tp:'5'},
{id:'109', bc:'Procure to Pay',pl1:'Accounts Payable',bm:'Percentage of invoice line items matched with a purchase order',bp:'0.213',md:'0.676',tp:'0.9'},
{id:'110', bc:'Procure to Pay',pl1:'Accounts Payable',bm:'Cycle time in hours to enter invoice data onto the system',bp:'72',md:'40',tp:'12.3'},
{id:'111', bc:'Procure to Pay',pl1:'Accounts Payable',bm:'Cycle time in days from receipt of invoice until approved and scheduled for payment',bp:'15.7',md:'7',tp:'4'},
{id:'112', bc:'Procure to Pay',pl1:'Accounts Payable',bm:'Cycle time in days to resolve an invoice error',bp:'14',md:'6.9',tp:'3'},
{id:'113', bc:'Procure to Pay',pl1:'Accounts Payable',bm:'Cycle time in days from receipt of invoice until payment is transmitted',bp:'42',md:'30',tp:'12'}]

export default EYBenchmarks;